---
title: "R Notebook"
output: rmarkdown::github_document
---



```{r}
glm(formula = supplementary_tables$pathogenicity ~ supplementary_tables$`polar to polar` + 
    supplementary_tables$`polar to non-polar` + supplementary_tables$`polar to charged` + 
    supplementary_tables$`non-polar to polar` + supplementary_tables$`non-polar to non-polar` + 
    supplementary_tables$`non-polar to charged` + supplementary_tables$`charged to polar` + 
    supplementary_tables$`charged to non-polar` + supplementary_tables$`charged to charged`, 
    family = binomial(link = "logit"))
```


Deviance Residuals: 
    Min       1Q   Median       3Q      Max  
-1.5616  -1.1168  -0.1146   1.2393   2.0679  

Coefficients:
                                              Estimate Std. Error z value Pr(>|z|)
(Intercept)                                   -0.14432    0.23320  -0.619  0.53599
supplementary_tables$`polar to polar`         -0.97160    0.40988  -2.370  0.01777
supplementary_tables$`polar to non-polar`      0.29818    0.32200   0.926  0.35444
supplementary_tables$`polar to charged`        0.53692    0.45053   1.192  0.23336
supplementary_tables$`non-polar to polar`     -0.10036    0.16050  -0.625  0.53177
supplementary_tables$`non-polar to non-polar` -0.17948    0.13600  -1.320  0.18691
supplementary_tables$`non-polar to charged`    1.30136    0.42619   3.053  0.00226
supplementary_tables$`charged to polar`        0.37210    0.21593   1.723  0.08485
supplementary_tables$`charged to non-polar`   -0.04952    0.45809  -0.108  0.91391
supplementary_tables$`charged to charged`     -0.88796    0.46141  -1.924  0.05430
                                                
(Intercept)                                     
supplementary_tables$`polar to polar`         * 
supplementary_tables$`polar to non-polar`       
supplementary_tables$`polar to charged`         
supplementary_tables$`non-polar to polar`       
supplementary_tables$`non-polar to non-polar`   
supplementary_tables$`non-polar to charged`   **
supplementary_tables$`charged to polar`       . 
supplementary_tables$`charged to non-polar`     
supplementary_tables$`charged to charged`     . 
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 163.58  on 117  degrees of freedom
Residual deviance: 134.89  on 108  degrees of freedom
  (13 observations deleted due to missingness)
AIC: 154.89

Number of Fisher Scoring iterations: 7